version: "3"
services:
  duckdns:
    image: linuxserver/duckdns:arm32v7-78f79e9f-ls75
    container_name: duckdns
    env_file: .env
    volumes:
     - './duckdns:/config'
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.8.1-armhf-stretch
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    env_file: .env
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
