services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    network_mode: 'host'
    env_file: .env
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
